/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.virtual.sr.transforms;

import com.hp.hpl.jena.query.Query;
import com.hp.hpl.jena.query.QueryExecutionFactory;
import com.hp.hpl.jena.query.QueryFactory;
import com.hp.hpl.jena.rdf.model.Model;
import org.virtual.sr.utils.Constants;

/**
 *
 * @author Claudio Baldassarre <c.baldassarre@me.com>
 */
public class Raw2CustomRdf {

    private static String query = ""
            + ""
//            + "#transformation working for FLOD custom sr_public "
            + " construct { "
            + ""
//            + "#-------coded entity related triples———"
            + " ?coded_entity a <http://www.fao.org/figis/flod/onto/codedentity.owl#CodedEntity> . \n"
            + " ?coded_entity <http://www.fao.org/figis/flod/onto/codedentityclassification.owl#isClassfiedByCode> ?code . \n"
            + " ?coded_entity <http://www.w3.org/2000/01/rdf-schema#label> ?code_label_str . \n"
            + " ?coded_entity <http://www.w3.org/2004/02/skos/core#prefLabel> ?code_label_str . \n"
            + ""
//            + "#-------codelist related triples--------"
            + " ?sr_public <http://rdfs.org/ns/void#Dataset> ?system . \n"
            + " ?system dct:creator ?creator . \n"
            + " ?system dct:hasVersion ?version . \n"
            + " ?system skos:editorialNote 'Generated by the Semantic Repository LOD maintenance framework' . \n"
            + " ?system skos:changeNote ?changeNote . \n"
            + ""
//            + "#-------code related triples--------"
            + " ?code a <http://www.fao.org/figis/flod/onto/linneanspecies.owl#SpeciesCode> . \n"
            + " ?code <http://www.fao.org/figis/flod/onto/codedentitycollection.owl#system> ?system . \n"
            + " ?code <http://www.w3.org/2000/01/rdf-schema#label> ?alpha_code . \n"
            + " ?code <http://www.ontologydesignpatterns.org/cp/owl/classification.owl#classifies> ?coded_entity \n"
            + " } "
            + ""
            + " where { "
            + " ?y j.0:Prepared ?changeNote . \n"
            + " ?x j.0:Codelist ?system_raw . \n"
            + " ?system_raw j.0:urn ?system_urn . \n"
            + " ?system_raw j.0:version ?version . \n"
            + " ?system_raw j.0:agencyID ?creator . \n"
            + " ?system_raw j.0:id ?id . \n"
            + " BIND(IRI(fn:concat('http://www.fao.org/figis/flod/entities/codificationsystem/', fn:lower-case(STR(?id)))) as ?system) \n"
            + " BIND(IRI('http://www.fao.org/figis/flod/entities/sr_public/') as ?sr_public) \n"
            + ""
            + " ?t j.0:Code ?code_raw . \n"
            + " ?code_raw j.0:urn ?code_urn . \n"
            + " ?code_raw j.0:id ?alpha_code . \n"
            + " BIND(IRI(fn:concat('http://www.fao.org/figis/flod/entities/speciescode/', fn:lower-case(STR(?alpha_code)))) as ?code) \n"
            + " BIND(IRI(fn:concat('http://www.fao.org/figis/flod/entities/codedentity/', SHA1(STR(?code)))) as ?coded_entity) \n"
            + ""
            + ""
            + " OPTIONAL{?code_raw j.0:Name ?code_name . ?code_name j.0:Name ?code_label . ?code_name j.0:lang ?lang BIND(strlang(?code_label, str(?lang)) as ?code_label_str)}. \n"
            + "}";

    public static Model FLODcustomize(Model rdf) {
        Query trasnformationQuery = QueryFactory.create(Constants.prefixes + query);
        Model transformedModel = QueryExecutionFactory.create(trasnformationQuery, rdf).execConstruct();
        return transformedModel;

    }
}
